Meal Menu
maenkhraisha/JavaScript-capstone-2 pull request #31
Opened 2022-04-27 09:23 UTC by maenkhraisha

Features:
this application displays a list of meals from API.
you can add like for any meal
you can add comment 
you can add reservation with details for any meal

2022-04-27 10:50 UTC, brytebee requested changes
Hi, @ekenecf, @collinsmezie  & @maenkhraisha👋, 

Good job so far!
 
### Highlights 💡💡
 - A well-documented project. The README is professional.✔️ 
 - A good video presentation.✔️ 
 - The App fetches data using an API.✔️ 
 - The App likes, comments and reservation works great and use the Involvement API.✔️ 
 - Counters are present in all the interfaces.✔️

There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Changes Required ♻️ 

### Optional changes
- Your project has some files in the root directory. It is best for organizations to keep these files viz: `index.html`, `index.js`, `style.css` and `jumpy.gif` in the `src` or its children folders.

_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.  

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-04-27 10:50 UTC, brytebee commented on index.html
> +        <img id="img" src="./src/assets/images/jumpy.gif" alt="logo" width="100" height="100">
- [ ] **Required:** This logo works in the live demo but not in the local project. Kindly fix it. 

![image](https://user-images.githubusercontent.com/27709832/165499403-a7ecb669-f611-417b-9e61-ecaae7f640da.png)

2022-04-27 10:50 UTC, brytebee commented on index.html
> +        <!-- <img src= "assets/images/foodlogo.png" alt="logo"> -->
- [ ] **Required:** Kindly remove all commented code. It is unprofessional to push commented code.

2022-04-27 10:50 UTC, brytebee commented on README.md
> +[LIVE DEMO LINK](https://maenkhraisha.github.io/JavaScript-capstone-2/)
- [ ] **Optional:** Your live link is broken, it does not display the dishes, kindly fix this.

2022-04-27 10:50 UTC, brytebee commented on README.md
> +- https://drive.google.com/file/d/1z7djEMoRGty2ed6CYeEegKiq8YfQewDc/view?usp=sharing
- [ ] **Optional:** A wonderful presentation. Kudos. However, for future projects, kindly ensure your presentation is summarized within the stipulated time.

- [ ] **Optional:** @ekenecf Kindly make videos with more professional backgrounds going forward. A background where there is no movement behind and background noise.

2022-04-27 10:50 UTC, brytebee commented on README.md
> +- LinkedIn: [collins mezie](https://www.linkedin.com/in/collinsmezie/), [Ekene Emeka](https://www.linkedin.com/mwlite/in/ekene-nwachukwu-1b9024153) and [Maen Khraisha](https://www.linkedin.com/in/ma-
👏 👏 Awesome!!

2022-04-27 10:50 UTC, brytebee commented on index.js
> +/* eslint-disable no-use-before-define */
- [ ] **Optional:** These linters show up because of lines 1 and 2. You have not used the style or jumpy.

2022-04-28 04:04 UTC, medaminedev66 approved these changes
## Hi @maenkhraisha , @collinsmezie and @ekenecf

# Status: Approved ✔️
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚢
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-28 04:04 UTC, medaminedev66 commented on src/Module/counters.js
> +/* eslint-disable no-undef */
[OPTIONAL] Rather than disable the linter strive to fix them as this makes you more accustomed to the style guide of the tech.

2022-04-28 04:04 UTC, medaminedev66 commented on index.js
> +/* eslint-disable no-use-before-define */
[optional] Rather than disable the linter strive to fix them as this makes you more accustomed to the style guide of the tech.

2022-04-28 13:14 UTC, merged